name: PR Checks

on: pull_request

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
  run_checks:
    name: Run Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      